server {
    listen 80;
    listen [::]:80;
    server_name www.reseptor.no;

    return 301 http://reseptor.no$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name reseptor.no;

    root /var/www/reseptor/current;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /favicon.svg {
        access_log off;
        log_not_found off;
    }
}
